config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'blogs#index'
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :show, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def confirm
    @blog = Blog.new(blog_params)
  end

  def create
    if blog_params[:content].size >= 1 && blog_params[:content].size <= 140
      @blog = Blog.create(blog_params)
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render 'new'
      end
    else
      redirect_to blogs_path, notice: "送信に失敗しました。コメントは1〜140字でお願いいたします。"
    end
  end

  def edit
  end

  def update
    @blog = Blog.find(params[:id])
    if blog_params[:content].size >= 1 && blog_params[:content].size <= 140
      if @blog.update(blog_params)
        redirect_to blogs_path, notice: "ブログを編集しました"
      else
        render 'edit'
      end
    else
      redirect_to blog_path, notice: "送信に失敗しました。コメントは1〜140字でお願いいたします。"
    end
  end

  def show
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました"
  end

  private
  def blog_params
    params.require(:blog).permit(:id, :created_at, :title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div id="wrapper">
  <%= form_with(model: @blog,url: confirm_blogs_path, local:true) do |form|%>
  <p><%= notice %></p>
  <div class="blog clearfix">
    <span>title</span>
    <h3><%= form.text_field :title, class:"blog_title" %></h3>
    <span>content</span>
    <%= form.text_area :content %>
    <div class="buttons">
      <%= form.submit %>
    </div>
  </div>
  <% end %>
  <%= link_to "ブログ一覧画面にもどる", blogs_path %>
</div>

app/views/blogs/confirm.html.erb
<div id="wrapper">
  <h3>下記の内容で送信する</h3>
  <%= form_with(model: @blog, url: blogs_path, local: true) do |form|%>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
  <div class="blog clearfix">
    <span>title</span>
    <h3><%= @blog.title%></h3>
    <span>content</span>
    <div><%= @blog.content %></div>
    <div class="buttons">
      <%= form.submit "登録する" %>
    </div>
  </div>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<%= form_with(model:@blog, local:true) do |form| %>
<div id="wrapper">
  <h1>ブログ編集</h1>
  <p><%= notice %></p>
  <div class="blog clearfix">
    <div class="clearfix"><span class="blog_id"><%= @blog.id %></span><span class="blog_date"><%= @blog.created_at.strftime("%Y-%m-%d %H:%M") %></span>
    </div>
    <span>Title</span>
    <h3><%= form.text_field :title, class:"blog_title" %></h3>
    <span>Content</span>
    <%= form.text_area :content %>
    <div class="buttons">
      <%= form.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/blogs/index.html.erb
<div id="wrapper">
  <h1>ブログ</h1>
  <p><%= notice %></p>
  <%= link_to 'ブログ新規作成', new_blog_path %>
  <% @blogs.each do |blog| %>
  <div class="blog clearfix">
    <div><span class="blog_id"><%= blog.id %></span><span class="blog_date"><%= blog.created_at.strftime("%Y-%m-%d %H:%M") %></span></div>
    <h3><%= blog.title %></h3>
    <p><%= blog.content %></p>
    <div class="buttons">
      <%= link_to '確認', blog_path(blog.id) %>
      <%= link_to '編集', edit_blog_path(blog.id) %>
      <%= link_to '×', blog_path(blog.id), method: :delete %>
    </div>
  </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div id="wrapper"><h1>ブログ作成</h1></div>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div id="wrapper">
  <h1>ブログ確認</h1>
  <p><%= notice %></p>
  <div class="blog clearfix">
    <div><span class="blog_id"><%= @blog.id %></span><span class="blog_date"><%= @blog.created_at.strftime("%Y-%m-%d %H:%M") %></span></div>
    <h3><%= @blog.title %></h3>
    <p><%= @blog.content %></p>
  </div>
  <%= link_to 'ブログ一覧に戻る', blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>